version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: north_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: north_db
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
    restart: always
